name = "portfolio-v2"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_CV_URL = "https://s3.eu-central-1.amazonaws.com/attila.huszar/portfolio/Attila_Huszar_CV.pdf"
